#!/bin/bash
#
# Originally copied from "bin/fetch-from-genbank" in nextstrain/ncov-ingest:
#   https://github.com/nextstrain/ncov-ingest/blob/2a5f255329ee5bdf0cabc8b8827a700c92becbe4/bin/fetch-from-genbank
#
set -euo pipefail

bin="$(dirname "$0")"


main() {
    declare -a filters
    declare -a fields

    for arg; do
        case "$arg" in
            --filter=*)
                filters+=("${arg#*=}")
                shift;;
            --field=*)
                fields+=("${arg#*=}")
                shift;;
            *)
                break;;
        esac
    done

    local ncbi_taxon_id="${1:?NCBI taxon id is required.}"
    local ncbi_virus_url
    ncbi_virus_url="$("$bin"/ncbi-virus-url --ncbi-taxon-id "$ncbi_taxon_id" --filters "${filters[@]}" --fields "${fields[@]}")"

    fetch "$ncbi_virus_url" | "$bin"/csv-to-ndjson
}

fetch() {
    curl "$1" \
        --fail --silent --show-error --http1.1 \
        --header 'User-Agent: https://github.com/nextstrain/monkeypox (hello@nextstrain.org)'
}

main "$@"
